Algoritmo "exercicio07"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : jailson Santos
// Descrição   :
// Autor(a)    : Pedro Henrique
// Data atual  : 22/04/2026
Var
   // Seção de Declarações das variáveis
   raio, area: real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval ("Digite o valor do raio do circulo")
   leia (raio)

   area <- 3.14 * (raio ^ 2)

   Escreval("O valor da área do círculo é: ", area)
Fimalgoritmo