Algoritmo "exercicio01"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : jailson Santos
// Descrição   : Leia dois números inteiros informados pelo usuário e calcule
// a soma entre eles.
// Autor(a)    : Pedro Henrique
// Data atual  : 22/04/2026
Var
// Seção de Declarações das variáveis 
 numero1, numero2, soma: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um número: ")
   leia(numero1)

   Escreval("Digite outro número: ")
   leia(numero2)

   soma <- numero1 + numero2

   Escreval("A soma dos números é: ", soma)

Fimalgoritmo