Algoritmo "exercicio03"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : jailson Santos
// Descrição   : Leia o valor do lado de um quadrado e calcule o perímetro.
// Autor(a)    : Pedro Henrique
// Data atual  : 22/04/2026
Var
// Seção de Declarações das variáveis 
lado, perimetro: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite o valor do lado do quadrado: ")
   leia(lado)

   perimetro <- 4 * lado

   Escreval("O perímetro do quadrado é: ", perimetro)

Fimalgoritmo