Algoritmo "exercicio11"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : jailson Santos
// Descrição   : Leia a base e a altura de um paralelogramo e calcule sua área.
// Autor(a)    : Pedro Henrique
// Data atual  : 22/04/2026
Var
// Seção de Declarações das variáveis 
  base, altura, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreval("Digite o valor da base do paralelogramo: ")
   Leia(base)

   Escreval("Digite o valor da altura do paralelogramo: ")
   Leia(altura)

   area <- base * altura

   Escreval("O valor da área do paralelogramo é: ", area)

Fimalgoritmo