Algoritmo "exercicio08"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : jailson Santos
// Descrição   : Leia o raio de um círculo e calcule o comprimento da
// circunferência.
// Autor(a)    : Pedro Henrique
// Data atual  : 22/04/2026
Var
// Seção de Declarações das variáveis 
 raio, circunferencia: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreval("Digite o valor do raio do círculo: ")
   leia(raio)

   circunferencia <- 2 * 3.14 * raio

   Escreval("O comprimento da circunferência é: ", circunferencia)

Fimalgoritmo