Algoritmo "exercicio04"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : jailson Santos
// Descrição   : Leia a base e a altura de um retângulo e calcule sua área.
// Autor(a)    : Pedro Henrique
// Data atual  : 22/04/2026
Var
// Seção de Declarações das variáveis 
 base, altura, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreval("Digite a base do retângulo: ")
   leia(base)

   Escreval("Digite a altura do retângulo: ")
   leia(altura)

   area <- base * altura

   Escreval("A área do retângulo é: ", area)

Fimalgoritmo