Algoritmo "exercicio23"
// Disciplina   : [Lógica de Programação VisualG]
// Professor   : jailson Santos
// Descrição   : Ler um valor e escrever se é positivo ou negativo (considere
// o valor zero como positivo).
// Autor(a)    : Pedro Henrique
// Data atual  : 20/04/2026
Var
   // Seção de Declarações das variáveis
   numero: real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite um número")
   leia(numero)
   se numero < 0 então
      Escreval("Número digitado é negativo")
   senao numero > 0 então
      escreval("Número digitado é positivo")
   fimse


Fimalgoritmo