Algoritmo "PAGINA25-I"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson Santos
// Descrição: Calcular o quadrado da diferenca entre dois valores
// Autor(a): Pedro Henrique
// Data atual: 19/04/2026
Var
   // Seção de Declarações das variáveis
   a, b, resultado: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
  Escreval("Digite o valor de A: ")
   leia(a)
   Escreval("Digite o valor de B: ")
   leia(b)
   resultado <- (a - b) * (a - b)

   Escreval("O quadrado da diferenca entre A e B é : ", resultado)

Fimalgoritmo