Algoritmo "PAGINA25-F"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson Santos
// Descrição: Trocar os valores de A e B
// Autor(a): Pedro henrique
// Data atual: 19/04/2026
Var
   // Seção de Declarações das variáveis
   a, b: caractere
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite o valor de A : ")
   leia(a)
   Escreval("Digite o valor de B : ")
   leia(b)

   Escreval("O novo valor de A é : ", b)
   Escreval("O novo valor de B é : ", a)

Fimalgoritmo