Algoritmo "PAGINA25-G"
// Disciplina: [Lógica de Programação com visualG]
// Professor: Jailson Santos
// Descrição: Somar e multiplicar os valores entre si
// Autor(a): Pedro Henrique
// Data atual: 19/04/2026
Var
   // Seção de Declarações das variáveis
   a, b, c, d: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite o valor de A: ")
   leia(a)
   Escreval("Digite o valor de B: ")
   leia(b)
   Escreval("Digite o valor de C: ")
   leia(c)
   Escreval("Digite o valor de D: ")
   leia(d)
   Escreval("A + B = ", a + b)
   Escreval("A * B = ", a * b)

   Escreval("A + C = ", a + c)
   Escreval("A * C = ", a * c)

   Escreval("A + D = ", a + d)
   Escreval("A * D = ", a * d)

   Escreval("B + C = ", b + c)
   Escreval("B * C = ", b * c)

   Escreval("B + D = ", b + d)
   Escreval("B * D = ", b * d)

   Escreval("C + D = ", c + d)
   Escreval("C * D = ", c * d)

Fimalgoritmo